### ISSUE TITLE
接口频率限流

### ISSUE THREAD

**Issue by pengweibo** [DDAaTao/ip-limiter#1]
现在是还没有做接口频率限流吗

**Comment by DDAaTao** [comment]
是支持接口频率限流的

一、 如何在接口上进行限流
直接在接口上添加 @IpLimit 注解即可
![image](https://github.com/DDAaTao/ip-limiter/assets/40759535/34166143-0d3f-4796-a2b6-28d9a5127afd)

二、如何控制接口的限流频率
根据注解中的 unitTime、limitTimeType、maxTimes配置，将要想的限流频率拆分为这三个字段即可
![image](https://github.com/DDAaTao/ip-limiter/assets/40759535/784e4d87-dfb7-45bf-8f47-c095db92e199)
